# Generated by Django 5.2.7 on 2025-12-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_eventregistration_comment_eventregistration_rating'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', 'notification_read'], name='idx_user_notification_read'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'attended'], name='idx_event_attended'),
        ),
    ]
