# Generated by helper to remove unwanted category

from django.db import migrations

def remove_technology_category(apps, schema_editor):
    Category = apps.get_model('event_management', 'Category')
    # Borrar 'Tecnología' y 'Tecnológico' por si acaso
    Category.objects.filter(name__in=['Tecnología', 'Tecnológico']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_create_default_categories'),
    ]

    operations = [
        migrations.RunPython(remove_technology_category),
    ]
